# Generated by Django 4.1.1 on 2022-09-20 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='employees',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('department_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='home.department')),
            ],
        ),
    ]
